name: dropdown_button2_workspace
repository: https://github.com/AhmedLSayed9/dropdown_button2

packages:
  - packages/**
  - examples/**

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    run: |
      melos exec -c 10 -- \
        flutter analyze --fatal-infos
    description: Run `flutter analyze` for all packages.

  format:
    run: melos exec dart format . --line-length=100 --fix
    description: Run `dart format` for all packages.

  test:select:
    run: melos exec -- flutter test
    packageFilters:
      dirExists: test
    description: Run `flutter test` for selected packages.

  test:
    run: melos run test:select --no-select
    description: Run all Flutter tests in this project.

  coverage:
    run: |
      melos exec -- flutter test --coverage &&
      melos exec -- genhtml coverage/lcov.info --output-directory=coverage/
    packageFilters:
      dirExists: test
    description: Generate coverage for the selected package.

  update-goldens:
    run: melos exec -- flutter test --update-goldens
    packageFilters:
      dirExists: test
    description: Re-generate all golden test files
