include: ../../analysis_options.yaml

linter:
  rules:
    # Not useful for tests
    avoid_redundant_argument_values: false
    omit_obvious_local_variable_types: false
    public_member_api_docs: false
    specify_nonobvious_property_types: false
