name: dropdown_button2_test
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1

  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  file: ^7.0.0
  platform: ^3.1.0

flutter:
  fonts:
    # Used for golden tests
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  assets:
    - assets/images/
